/** @type {import('tailwindcss').Config} */
export default {
  content: ["./index.html", "./src/**/*.{js,ts,jsx,tsx}"],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "tertiary": "#6a5f00",
        "on-secondary-container": "#546474",
        "on-tertiary-fixed": "#201c00",
        "on-secondary-fixed-variant": "#384858",
        "outline-variant": "#c5c6cd",
        "secondary-container": "#d0e2f5",
        "inverse-primary": "#bbc6e2",
        "surface-tint": "#545e76",
        "error-container": "#ffdad6",
        "tertiary-fixed": "#f5e479",
        "on-primary": "#ffffff",
        "on-primary-fixed-variant": "#3c475d",
        "on-error-container": "#93000a",
        "secondary": "#4f6070",
        "surface-container-lowest": "#ffffff",
        "on-primary-fixed": "#101b30",
        "error": "#ba1a1a",
        "background": "#f8f9fa",
        "surface": "#f8f9fa",
        "surface-container-low": "#f3f4f5",
        "surface-container": "#edeeef",
        "secondary-fixed-dim": "#b7c8db",
        "outline": "#75777d",
        "primary-fixed": "#d7e2ff",
        "surface-bright": "#f8f9fa",
        "on-secondary": "#ffffff",
        "on-secondary-fixed": "#0b1d2b",
        "primary-container": "#1b263b",
        "on-background": "#191c1d",
        "surface-variant": "#e1e3e4",
        "secondary-fixed": "#d3e4f7",
        "on-surface-variant": "#45474d",
        "surface-container-highest": "#e1e3e4",
        "on-error": "#ffffff",
        "tertiary-container": "#bcac48",
        "on-tertiary-container": "#484000",
        "on-tertiary-fixed-variant": "#504700",
        "surface-container-high": "#e7e8e9",
        "inverse-on-surface": "#f0f1f2",
        "primary": "#051125",
        "surface-dim": "#d9dadb",
        "primary-fixed-dim": "#bbc6e2",
        "inverse-surface": "#2e3132",
        "tertiary-fixed-dim": "#d8c860",
        "on-tertiary": "#ffffff",
        "on-surface": "#191c1d",
        "on-primary-container": "#828da7",
      },

      borderRadius: {
        DEFAULT: "0.125rem",
        lg: "0.25rem",
        xl: "0.5rem",
        full: "0.75rem",
      },

      fontFamily: {
        headline: ["Noto Serif"],
        body: ["Manrope"],
        label: ["Manrope"],
      },
    },
  },
  plugins: [],
}

